---
- hosts: localhost
  connection: local
  gather_facts: false
  
  tasks: 
    - name: copy .ansible.cfg file at user's home dir
      copy: 
        src: files/.ansible.cfg
        dest: ~/

    - name: copy ssh.cfg file 
      copy:
        src: files/news-app-ssh.cfg
        dest: /tmp/

#    - name: Download and Install terraform
#      ansible.builtin.unarchive:
#        src: https://releases.hashicorp.com/terraform/0.12.30/terraform_0.12.30_linux_amd64.zip
#        dest: /usr/local/bin
#        remote_src: yes

    - name: init terraform
      shell: /usr/local/bin/terraform init
      args:
        chdir: terraform/
      environment:
        aws_secret_access_key: "{{ lookup('cypher','secret=tfvars/TerraformAnsible')|to_json|json_query('aws_secret_access_key') }}"
        aws_access_key_id: "{{ lookup('cypher','secret=tfvars/TerraformAnsible')|to_json|json_query('aws_access_key_id') }}"
      vars:
          private_key_name: a_wrong_value
          private_key_file_path: a_wrong_value
          ssh_location: 0.0.0.0/0

    - name: plan terraform script
      check_mode: yes
      environment:
        AWS_SECRET_ACCESS_KEY: "{{ lookup('cypher','secret=tfvars/TerraformAnsible')|json_query('aws_secret_access_key') }}"
        AWS_ACCESS_KEY_ID: "{{ lookup('cypher','secret=tfvars/TerraformAnsible')|json_query('aws_access_key_id') }}"
      terraform:
        binary_path: /usr/local/bin/terraform
        project_path: terraform/
        state: present


    - name: plan terraform script
      check_mode: yes
      environment:
        AWS_SECRET_ACCESS_KEY: "{{ lookup('cypher','secret=tfvars/TerraformAnsible')|json_query('aws_secret_access_key') }}"
        AWS_ACCESS_KEY_ID: "{{ lookup('cypher','secret=tfvars/TerraformAnsible')|json_query('aws_access_key_id') }}"
      terraform:
        binary_path: /usr/local/bin/terraform
        project_path: terraform/
        state: present
